### ISSUE TITLE
Checkpoint 1 Ready for Review

### ISSUE THREAD

**Issue by SapphireStar31** [SapphireStar31/recipe-searcher#1]
@pawaitemadisoncollege

I believe I have everything for the checkpoint ready. I filled out my project plan to week 6, but I am unsure of how to proceed from that week on. I feel like on week 5 once I know better where I am at in the project and where I am going, I can plan out some more weeks to get myself back on track or keep on track of schedule. Otherwise, if you prefer I try to put something for the weeks after that I can try. 

The forms on my screen design for adding recipes will probably change as well. Right now there is a text area, but I don't think that will be the right thing to put there so I am gonna research more on whats best for listing multiple ingredients and how it works. Then finally I think I have kinda slimed it down on function that the recipe will just hold the ingredients but not the actual recipe (meaning no amount of ingredients or actual directions for making it). This will hopefully make it easier to see actual different recipes to try instead of 30 recipes for the same thing (which is what I am trying to get around since I hate it when this happens with Google). I would love feedback if you think thats a good idea or if you think that I might have made things harder on myself and it is better to hold actual directions and amounts too. 

Then I have a question with the requirements, one says "Web service/s (at least one) consumed using Java" is this something we will learn about or is it something we have learned about in one of the previous classes and I should go refresh myself on it?

**Comment by pawaitemadisoncollege** [comment]
Hi @SapphireStar31 !

**Problem statement** 

Does a good job clearly explaining the problem and the solution. The egg example helps make this really clear.

- [x] readme.md would be improved with some markdown formatting, like making  "Problem Statement" and "Goal" headings. You can get an idea of how to do this by viewing the raw markdown for any of the exercises or demo repositories, or by using this reference: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax. 

- [x] The readme would be a good place to also include the tech used in the project. Think of what you'd like to communicate to those, like prospective employers, viewing your repo.

- [x] I noticed your design documents are in a checkpoint 1 folder. This would be better named something like "design documents" as these are living documents that you will use for the lifetime of your project. "Checkpoint1" won't mean much to anyone outside of this class viewing your repo.

**User stories w/ MVP stories identified** Your users stories are clear and well-written following the best practices for user stories. They clearly communicate what your application will do. Your MVP stories seem to include what's needed for the ent java project requirements like crud, and multiple tables with more than one one-to-many relationship. I think you've done a good job scoping the project to what's doable this semester!

- [x] Does a user need to be logged in to all activities or only some of them? Is there a difference between a user who can search for a recipe versus a user who can add one? If so, make this clear by specifying, "As a logged in user" or maybe "as a guest user". Use whatever makes sense to you!

- [x] Since the goal of your application is to make sure there are a bunch of recipes for the same thing, I'm curious how you will manage this. How can you prevent Scrambled Eggs 1, Scrambled Eggs 2, etc.?

- [x] Thinking about a web service/api that could be used in your project - we will cover how to consume restful apis with java code in week 8. 

For your application, I think you'll find a lot of options. For example, what if a user decides they want to make Eggs Benedict because  they found it on your site. What is next for them? Do they open a new browser window and start googling or?? You could provided an option to get them a recipe using something like: https://developer.edamam.com/recipe-demo.  You can explore lots of apis here: https://rapidapi.com/hub

Another option, if you'd like to explore a java library rather than a service would be to use something like java mail - your application could provide a way for users to report a recipe that doesn't follow the rules and that process would send your admin an email.  

If there's something you think it would be cool if your application did, there may be some other apis or libraries that you can leverage to do it!

**Wireframes**. Good work on these! The wireframes clearly communicate what each page will do and I think all user stories are represented.  

- [x] Something to know is that we'll be using AWS cognito for sign up/sign in capability, so there are some screens that you may not have to worry about as they can be provided by Cognito itself.  We'll learn more about this in week 7.

- [x] I noticed a random recipe link, but didn't see a story for this.

- [x] I noticed dietary checkboxes that weren't referenced in any story. 

**Project Plan** A good start! This will definitely grow and change throughout the semester.

- [ ] I recommend at least identifying which user story you plan to work on each week to make sure you have everything accounted for.  

- [x] Tools like Chatgpt can be helpful brainstorming tasks if you are having trouble coming up with them. I think the more detailed you can be the better. What do you think about creating a task for each story to decide which jsp/s, controllers, entities, tables you'll need for that story.  

- [x] Revising the plan could be a task on the plan itself (woah!)

**Reflection/Time log** Keep up the good work with this. 

**********
**To reach "met" status for checkpoint 1:**

At minimum: Address the items listed under Problem Statement, and make sure  all MVP user stories are on your plan. 

You can respond here when those are ready for review.

**Comment by SapphireStar31** [comment]
@pawaitemadisoncollege I think I got it fixed up on the problem statement for what I know and added some more user stories to cover the parts of the wireframes I missed.

**Comment by pawaitemadisoncollege** [comment]
Those updates help make things more clear @SapphireStar31. Considering we are in week 6, can you now add each of your mvp user stories to the plan?

I also think the plan and user story list would be easier to read if saved as .md so your markdown renders when viewing the page on GitHub. https://github.com/SapphireStar31/recipe-searcher/blob/main/DesignDocuments/projectPlan.txt and https://github.com/SapphireStar31/recipe-searcher/blob/main/DesignDocuments/userStories.txt

**Comment by SapphireStar31** [comment]
@pawaitemadisoncollege 
I added some more weeks to the project plan and added in which user stories are being done on the weeks I have planned out. Let me know if that looks any better at all!

**Comment by pawaitemadisoncollege** [comment]
This is looking better @SapphireStar31! I hope it helps you tick off the tasks, and also understand what needs to be completed to hit the mark for the project.  

It looks like week 10 will be busy! Remember to move things around as you learn more. For example, we are in week 7 now, so some of the tasks from previous weeks should be either checked off as complete (if they are in fact done) or moved forward. 

Checkpoint 1 : met
